version: '3'
services:
  web:
    image: python:2
    container_name: flask-uwsgi
    ports:
      - "5000:5000"
    volumes:
      - .:/home
    stdin_open: true
    tty: true
    links:
      - redis

  redis:
    image: redis
    container_name: redis