version: '3'
services:
  web:
    build: .
    container_name: web
    ports:
      - "80:5000"
    volumes:
      - .:/home
    stdin_open: true
    tty: true
    links:
      - redis
      - db

  redis:
    image: redis
    container_name: redis

  db:
    image: mysql
    container_name: mysql
    expose:
      - "3306"
    environment:
      - MYSQL_DATABASE=mysitedb
      - MYSQL_ROOT_PASSWORD=951005